// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/events_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/events_service.go -destination=internal/service/mock/events_service_mock.go -package=servicemock
//

// Package servicemock is a generated GoMock package.
package servicemock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/events-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEventsService is a mock of EventsService interface.
type MockEventsService struct {
	ctrl     *gomock.Controller
	recorder *MockEventsServiceMockRecorder
	isgomock struct{}
}

// MockEventsServiceMockRecorder is the mock recorder for MockEventsService.
type MockEventsServiceMockRecorder struct {
	mock *MockEventsService
}

// NewMockEventsService creates a new mock instance.
func NewMockEventsService(ctrl *gomock.Controller) *MockEventsService {
	mock := &MockEventsService{ctrl: ctrl}
	mock.recorder = &MockEventsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsService) EXPECT() *MockEventsServiceMockRecorder {
	return m.recorder
}

// Feed mocks base method.
func (m *MockEventsService) Feed(ctx context.Context, userID uuid.UUID, limit int, before *time.Time) ([]*models.ActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, userID, limit, before)
	ret0, _ := ret[0].([]*models.ActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Feed indicates an expected call of Feed.
func (mr *MockEventsServiceMockRecorder) Feed(ctx, userID, limit, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockEventsService)(nil).Feed), ctx, userID, limit, before)
}

// Read mocks base method.
func (m *MockEventsService) Read(ctx context.Context, userID, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Read indicates an expected call of Read.
func (mr *MockEventsServiceMockRecorder) Read(ctx, userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockEventsService)(nil).Read), ctx, userID, eventID)
}

// ReadAll mocks base method.
func (m *MockEventsService) ReadAll(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockEventsServiceMockRecorder) ReadAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockEventsService)(nil).ReadAll), ctx, userID)
}

// Record mocks base method.
func (m *MockEventsService) Record(ctx context.Context, event *models.ActivityEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Record", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Record indicates an expected call of Record.
func (mr *MockEventsServiceMockRecorder) Record(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockEventsService)(nil).Record), ctx, event)
}

// Unread mocks base method.
func (m *MockEventsService) Unread(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unread", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unread indicates an expected call of Unread.
func (mr *MockEventsServiceMockRecorder) Unread(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unread", reflect.TypeOf((*MockEventsService)(nil).Unread), ctx, userID)
}
