// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/event_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/event_repository.go -destination=internal/repository/mock/event_repository_mock.go -package=repomock
//

// Package repomock is a generated GoMock package.
package repomock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	models "github.com/mrhumster/events-service/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockEventRepository) Insert(ctx context.Context, event *models.ActivityEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockEventRepositoryMockRecorder) Insert(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockEventRepository)(nil).Insert), ctx, event)
}

// ListByUser mocks base method.
func (m *MockEventRepository) ListByUser(ctx context.Context, userID uuid.UUID, limit int, before *time.Time) ([]*models.ActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, before)
	ret0, _ := ret[0].([]*models.ActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockEventRepositoryMockRecorder) ListByUser(ctx, userID, limit, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockEventRepository)(nil).ListByUser), ctx, userID, limit, before)
}

// MarkAllRead mocks base method.
func (m *MockEventRepository) MarkAllRead(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockEventRepositoryMockRecorder) MarkAllRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockEventRepository)(nil).MarkAllRead), ctx, userID)
}

// MarkRead mocks base method.
func (m *MockEventRepository) MarkRead(ctx context.Context, userID, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockEventRepositoryMockRecorder) MarkRead(ctx, userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockEventRepository)(nil).MarkRead), ctx, userID, eventID)
}

// UnreadCount mocks base method.
func (m *MockEventRepository) UnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadCount", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnreadCount indicates an expected call of UnreadCount.
func (mr *MockEventRepositoryMockRecorder) UnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadCount", reflect.TypeOf((*MockEventRepository)(nil).UnreadCount), ctx, userID)
}
